services:
  prometheus:
    image: prom/prometheus
    depends_on: [ node_exporter , cadvisor ]
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter

  cadvisor:
    image: google/cadvisor
    container_name: monitoring_cadvisor
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/kmsg:/dev/kmsg
    environment:
      - DOCKER_CGROUP_DRIVER=cgroupfs  # Forces cgroup v1 compatibility
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  grafana:
    image: grafana/grafana:latest
    depends_on: [ prometheus ]
    container_name: monitoring_grafana
    restart: unless-stopped
    ports:
      - "3006:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false


volumes:
  grafana_data:
  prometheus_data:
